# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en


# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 谢瑞桃的主页
  params:
   description: 谢瑞桃的主页
  menu:
   main:
      - name: 主页
        url: '#about'
        weight: 10
      - name: 教育经历
        url: '#education'
        weight: 15
      - name: 工作经历
        url: '#experience'
        weight: 20
      - name: 项目
        url: '#grants_experience'
        weight: 30    
      - name: 代表作
        url: '#featured'
        weight: 40
      - name: 论文
        url: '#publications'
        weight: 50
      - name: 课程
        url: '#courses'
        weight: 60
      - name: 联系方式
        url: '#contact'
        weight: 70
